okhv = "2.0"
repo = "https://github.com/OPEN-NEXT/LOSH-dummy-MOSH-D"
name = "LOSH-dummy-MOSH-D"
license = "CERN-OHL-S-2.0"
licensor = "Martin Häuer"
readme = "README.md"
image = "Documentation/ASM-image.png"
documentation-language = "en-GB"
technology-readiness-level = "OTLR-5"
function = "Doesn't do much, yet."
patent-class = "D03D 35/00"
tsdc = "MEC"
bom = "sBoM.csv"
outer-dimensions = "cube(size = [300,300,300]"
manufacturing-instructions = "Documentation/AssemblyGuide.md"

rpm = 666
