okhv = "2.0"
repo = "https://github.com/OPEN-NEXT/LOSH-dummy-MOSH-A"
name = "LOSH-dummy-MOSH-A"
spdx-license = "CERN-OHL-S-2.0"
licensor = "Martin Häuer"
readme = "README.md"
image = "/Documentation/ASM-image.png"
documentation-language = "en-GB"
project-stage = "prototype"
function = "Doesn't do much, yet."
patent-class = "D03D 35/00"
tsdc-id = "ASM-MEC"
simplified-bom = "sBoM.csv"
functional-metadata = "666 rpm"
manufacturing-process = "mechanical assembly"
outer-dimensions = "cube(size = [300,300,300]"
manufacturing-instruction = "/Documentation/AssemblyGuide.md"
