okhv = "2.0"
name = "Comb"
image = "../../Documentation/part-pictures/Parts_Print_3.jpg"
tsdc = "3DP"
material = "PLA"
smallest-tolerance-class = "m"
source = "CombModul.scad"
export = [
  "ombModul.pdf",
  "CombModul.stl"
]

[outer-dimensions]
width = 120
height = 100
depth = 3
