okhv = "2.0"
name = "Clamp Ring"
image = "../../Documentation/part-pictures/Parts_Print_2.jpg"
tsdc = "3DP"
material = "PLA"
source = "ClampRing.scad"
export = [
  "ClampRing.pdf",
  "ClampRing.stl"
]
smallest-tolerance-class = "m"

[outer-dimensions]
widht = 28
height = 30
depth = 28
